### ISSUE TITLE
Curl::curlToFile() may be malfunctioning

### ISSUE THREAD

**Issue by SOF3** [poggit/poggit#123]
This occasionally occurs, as the error message:

```
Oct 20 08:47:06.607 [dfca-3b0ab59d6a5721bc-EWR] UnexpectedValueException: Failed opening zip /tmp/.zipP5ZA5O: 19 in /poggit/src/poggit/ci/RepoZipball.php#44
#0 /poggit/src/poggit/webhook/PushHandler.php(60): poggit\ci\RepoZipball->__construct('repos/Infernus1...', '7f0c82c90a8f9be...', 'repos/Infernus1...', 0, NULL, 10485760)
#1 /poggit/src/poggit/webhook/GitHubWebhookModule.php(130): poggit\webhook\PushHandler->handle('Infernus101/Pro...', '1c376f4f9135068...')
#2 /poggit/src/poggit/webhook/GitHubWebhookModule.php(52): poggit\webhook\GitHubWebhookModule->output0('Infernus101/Pro...', '1c376f4f9135068...')
#3 /poggit/src/poggit/Meta.php(155): poggit\webhook\GitHubWebhookModule->output()
#4 /poggit/entry.php(47): poggit\Meta::execute('webhooks.gh.rep...')
#5 /var/www/html/index.php(23): include('/poggit/entry.p...')
#6 {main}
```

**Comment by SOF3** [comment]
Haven't reproduced this issue for weeks.
